---
title: "Multiple Choice Questions"
author: "Vaishali Chaudhuri"
date: "March 14 2015"
output: html_document
---

## Lecture 1a
  
What is the typeof variable d ?
```
f <- sqrt
x <- 1:20
y <- f(x)
z <- x^2
d <- data.frame(x, y, z)
```

* list
* dataframe
* integer
* character


## Lecture 1b

Consider the following code:What appears to be  the correct output of the [head(as.integer(in_circle))] ?
```
N <-10000
x <- runif(N)
y <- runif(N)
vlength<-sqrt<-(x^2 +y^2)
in_circle<-vlength < 1
```

* 1 1 1 1 1 0
* TRUE TRUE TRUE TRUE TRUE FALSE 
* 1 -1 1 0 -1 0
* 0.23, ,0.34, 0.12, 0.45, 0.55, 0.79


## Lecture 2a

What does the Central Limit Theorem state ?

* The distribution of the means of a set of random samples is approximately Normal
* The area under the normal denisty curve is one
* Measures of central tendency should always be computed with and without outliers
* Confidence intervals have zero margin of error for large sample sizes.


## Lecture 2b

Probability mass function is same as probability density function. what type of functions are they?

* False, the probability mass function is a discrete distribution and the probability density function is a continuous distribution
* True, they both are continuous distribution
* True, they both are discrete distribution
* False, the probability mass function is a continuous distribution and the probability density function is a discrete distribution


## Lecture 3a

In the following code . What is the result and typeof  [A%*%t(A)]
```
A <- matrix(1:4, nrow=1)
```

* 5 and integer
* (2X2) matrix and list
* A^2 and double
* A(inv) and integer


## Lecture 3b

Consider the eigen equation. If A is the identity matrix. what is lambda?

* lamba is equal to 1
* lambda is infinity
* lambda is zero value
* lamda  doesn't exist for an identity matrix

## Lecture 4a

Consider the following code:All the below lines of code perform the same function but have different levels of bracket or curly braces. would it affect the performance cost and which will be the fastest ? 
(Hint: R treats curly brackets as a “special” operator, whose arguments are not automatically evaluated, but it treats parentheses as a “built in” operator whose arguments (just one for parentheses) are evaluated automatically, with the results of this evaluation stored in a  list)
```
a <- function(x) x = 1/{
    1 + x
}
f <- function(x) x = 1/(1 + x)
g <- function(x) x = (1/(1 + x))
h <- function(x) x = ((1/(1 + x)))

x <- sample(1:100, 100, replace = TRUE)
comp <- microbenchmark(a(x), f(x), g(x), h(x), times = 1e+05)
comp
```

* 'a' will be the fastest because it has curly braces
* 'f' will be fastest because it has paranthesis
* all the operations have the same time because it is the same function and braces or parnatheses does not matter
* 'h' will be fastest because you are simplifying the function by adding layers of parantheses


## Lecture 4b

Consider the following code  does mean1 and mean2 have equal run times or differ in run times? 
```
mean1 <- function(x) mean(x)
mean2 <- function(x) sum(x) / length(x)
x <- runif(100)
stopifnot(all.equal(mean1(x), mean2(x)))
microbenchmark(
  mean1(x),
  mean2(x)
)
```

* mean1 is considerably slower  because  mean1 makes two passes over the vector to be more numerically accurate
* mean2 is considerably faster because just one inbuilt fnction is executed
* mean1 and mean2  have equal run time because they perform the same operation
* it cannot be determined from the above data


## Lecture 5a

Of the following which is not a valid way to read R data in a technically correct format
```
a<-read.xml
b<-read.csv
c<-read.table
d<-read.dataframe
```

* a & d
* a & b
* c & d
* All are correct formats to read R data


## Lecture 5b

In the following code what do the three dots represent?
```
maxMinusMin <- function(v, ...) max(v, ...) - min(v, ...)
apply(A, 1, maxMinusMin, na.rm=TRUE)
```

* Any additional parameter can be passed to the function but function is valid
* Function is invalid and cannot be executed
* It's an invalid function that will need more parameters
* Typing error

## Lecture 6a

In the following structure of data frame , what is one of the ways to query for the 
date
```
str(result)
'data.frame':   316125 obs. of  6 variables:
 $ ID    : int  1 2 3 4 5 6 7 8 9 10 ...
 $ dt    : Date, format: "1999-12-31" "1999-12-31" "1999-12-31" "1999-12-31" ...
 $ Ticker: chr  "0111145D US" "0113357D US" "0202445Q US" "0203524D US" ...
 $ px    : num  32.5 20.6 34.2 21.4 11 ...
 $ High  : num  34.9 23.5 35.4 25.9 11 ...
 $ Low   : num  31.19 18 28.85 20.28 9.97 ...
```

* create new character version of the dt variable (chardt) and query in sqldf on the character version of dt sqldf("SELECT * FROM result WHERE chardt='1999-12-31'")
* query the table by using the command ("SELECT * FROM result WHERE dt=",as.Date("1999-12-31"),"", sep=""))
* query the table by using the command ("SELECT * FROM result WHERE dt="1999-12-31")
* Date is in an integer format  and cannot be searched

## Lecture 6b

What is the dplyr (may also use magrittr package) approach(es) to search for a data point from a dataframe called 'flight' by 1st month and 1st DayofMonth
```
A<-flights[flights$Month==1 & flightsDayofMonth==1,]
B<-filter(flights, Month==1, DayofMonth==1)
C<-flights %>% select(Month==1) %>% select(DayofMOnth==1)
```


* B & C
* B
* C
* A

## Lecture 7a

The two most important properties of Tidyr package is :Each column is a variable and each row is an observation. Hence which statement is true

* It is easy to  describe functional relationships between columns than between rows
* It is easy to  describe functional relationships between rows than between columns
* Row and columns both are attributes of a dataframe , so each datapoint has a relationship with another datapoint across the dataframe
* All data points in a row are independent observations , hence there is no relationships even across a row in a dataframe

## Lecture 7b

In the following code what does the function xtab do ?
```
T_shirts <- data.frame(
  sex=sample(c("M","F"), 100, replace=T), 
  size=sample(c("L", "M", "S"), 100, replace=T)
)
table(T_shirts)
xtabs(~ sex + size, T_shirts)
```

* Crosstabulates variables with small numbers of unique values
* Introduces equally spaces tabs between columns in the output file
* Eliminates duplicate data in a table and merges data
* Breaks one data  frame into separate dataframes depending on the arguments that are passed to to xtab









## Lecture 1a

Which symbol is used to collect a variable number of function arguments?

* `...`
* `???`
* `+++`
* `yada, yada, yada`

## Lecture 1b

In the following code, what is the type of the variable `v`?
```
v <- runif(10) < 0.5
```

* logical
* numeric
* integer
* character

## Lecture 2a

The standard normal distribution has a mean of 0 and a standard deviation of 1, and the area under this curve over all possible x-values is one. What is the area under the curve of a normal probability distribution function with a standard deviation of 2?

* 1
* 2
* 2 &pi;
* 4

## Lecture 2b

Consider a sequence of 10 coin flips, represented by the string `TTTHTHTTTH`. Which statement gives the total number of different sequences of 10 coin flips that could result in this number of heads?

* `choose(10,3)`
* `factorial(10)/(factorial(4)*factorial(7))`
* `integrate(dnorm, -Inf, 0)`
* `sapply(3:10, function(x) factorial(x))`

## Lecture 2b again

Consider the following code:
```
coinflips <- strsplit('TTTHTHTTTH','')[[1]]
flip10 <- sapply(1:10000, function(i) paste(sample(coinflips),collapse=''))
length(unique(flip10))
```
What does the variable `flip10` contain?

* Ten thousand permutations, each with 3 heads and 7 tails
* A function for flipping ten coins
* An estimate of the number of possible permutations of the given sequence
* A vector of 10 'H' and 'T' characters

## Lecture 3a

Which command will create a multiplication table for the numbers from 1 to 10?
Assume `r` is a row vector defined like this: `r <- matrix(1:10,1)`

* t(r) %*% r
* r %*% t(r)
* r^2
* t(r)^2

## Lecture 3b

Given a 2 by 2 matrix `A <- matrix(c(2, 5, 3, 8), 2, byrow=TRUE)`, which command performs Gaussian elimination to put A in upper triangular form?

* A[2,] <- A[2,] - A[1,] * 3/2
* A[3,] <- A[3,] - A[2,]
* A[2,] <- A[1,] * 3/8
* A[2,] <- A[2,] + A[1,] + A[1,]/2


## Lecture 4a

Here is code to add normally distributed noise to an input vector:
```
addRandom <- function(i) i + rnorm(1)
y <- sapply(0:10, addRandom)
```
How would you change `addRandom` to a vectorized version that could be used like this:
`y <- addRandom(0:10)`? (Choose the best solution)

* `addRandomVectorized <- function(v) v + rnorm(length(v))`
* `addRandomVectorized <- function(i) vapply(i, function(x) x+rnorm(1), 1)`
* `addRandomVectorized <- function(x) sapply(x, addRandom)`
* `addRandomVectorized <- Vectorize(addRandom)`

## Lecture 4b

Consider the following profiling results:
```
             self.time self.pct
"function_A"    278.39    86.46
"function_B"     29.32     9.10
"function_C"     14.29     4.44
```
If you make `function_B` 100 times faster, how much faster would you expect the program be?

* less than 10% faster
* twice as fast
* 100 times as fast
* no faster

## Lecture 5a

Which of the regular expressions below matches this sentence exactly once?
"The key, the whole key, and nothing but the key."

* "\\.$"
* "[Tt]he\\s"
* "(and|not)"
* "?key?"

## Lecture 5b

Which of these addresses cannot be read by the built-in `url()` function?

* `https://connect.usfca.edu`
* `http://rseek.org/`
* `http://ftp.ics.uci.edu/pub/machine-learning-databases/`
* `file:///usr/share/dict/words`

## Lecture 6a

How may rows are returned by the following query?
```
A <- data.frame(a=1:10)
B <- data.frame(b=5:15)
sqldf::sqldf("SELECT * FROM A JOIN B ON a==b")
```

* 6
* 10
* 8
* none

## Lecture 6b

Which command opens a connection to an SQLite database?

* dsets <- dbConnect(RSQLite::SQLite(), "datasets.sqlite")
* res <- dbSendQuery(dsets, "select * from iris limit 10")
* sqliteCopyDatabase(dsets, "datasets.sqlite")
* dbListTables(dsets)

## Lecture 7a

Which command is equivalent to this pipeline?
`myData %>% group_by(sex) %>% summarise(avg_price=mean(price))`

* `summarize(group_by(myData, sex), avg_price=mean(price))`
* `mean(avg_price, group_by(myData, sex), summarise)`
* `summarise(myData[, "sex"], avg_price=mean(price), group_by(myData))`
* `lapply(myData, function(sex){ group_by(sex); avg_price=mean(price)})